export const MEETING_PILOT_STATE_KEY = 'meetingPilotState';

export const MEETING_MESSAGE = {
  CONTENT_SIGNAL: 'MEETING_PILOT_CONTENT_SIGNAL',
  GET_STATE: 'MEETING_PILOT_GET_STATE',
  OPEN_PANEL: 'MEETING_PILOT_OPEN_PANEL',
  OPEN_LIVE_MAP: 'MEETING_PILOT_OPEN_LIVE_MAP',
  START: 'MEETING_PILOT_START',
  STOP: 'MEETING_PILOT_STOP',
  CATCH_UP: 'MEETING_PILOT_CATCH_UP',
  OFFSCREEN_START: 'MEETING_PILOT_OFFSCREEN_START',
  OFFSCREEN_STOP: 'MEETING_PILOT_OFFSCREEN_STOP',
  OFFSCREEN_GET_STATUS: 'MEETING_PILOT_OFFSCREEN_GET_STATUS',
  CAPTURE_EVENT: 'MEETING_PILOT_CAPTURE_EVENT',
  TRANSCRIPT_CHUNK: 'MEETING_PILOT_TRANSCRIPT_CHUNK',
  CONFIG_UPDATE: 'MEETING_PILOT_CONFIG_UPDATE',
} as const;

export const MEETING_CAPTURE_MIME_TYPES = [
  'video/webm;codecs=vp9,opus',
  'video/webm;codecs=vp8,opus',
  'video/webm',
];

export const MEETING_AUDIO_MIME_TYPES = [
  'audio/webm;codecs=opus',
  'audio/webm',
];
